// Auto-generated by LibreLane
module control_systolic(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input a_ready,
  input b_ready,
  input[7:0] D_a_00,
  input[7:0] D_a_10,
  input[7:0] D_b_00,
  input[7:0] D_b_01,
  input[2:0] num_matrix,
  output[31:0] D_c_flat,
  output systolic_busy,
  output systolic_free
);
endmodule
